src/Entity/Roles.php
<?php

namespace App\Entity;

use App\Repository\RolesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=RolesRepository::class)
 */
class Roles
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $label;

    /**
     * @ORM\OneToMany(targetEntity=Users::class, mappedBy="id_role")
     */
    private $users;

    public function __construct()
    {
        $this->users = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLabel(): ?string
    {
        return $this->label;
    }

    public function setLabel(string $label): self
    {
        $this->label = $label;

        return $this;
    }

    /**
     * @return Collection<int, Users>
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(Users $user): self
    {
        if (!$this->users->contains($user)) {
            $this->users[] = $user;
            $user->setIdRole($this);
        }

        return $this;
    }

    public function removeUser(Users $user): self
    {
        if ($this->users->removeElement($user)) {
            // set the owning side to null (unless already changed)
            if ($user->getIdRole() === $this) {
                $user->setIdRole(null);
            }
        }

        return $this;
    }
}

src/Entity/Users.php
<?php

namespace App\Entity;

use App\Repository\UsersRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=UsersRepository::class)
 * @ORM\Table(name="Users")
 * @UniqueEntity(fields={"username"},message="le nom d'utilisateur doit être unique")
 * @method string getUserIdentifier()
 */
class Users implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $username;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="veuillez encoder un mot de passe",groups="registration")
     * @Assert\Regex(pattern="/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[#$^+=!*()@%&]).{8}$/",
     *     htmlPattern="^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[#$^+=!*()@%&]).{8}$",
     *     message="le password doit contenir au moins 1 majuscule, 1 caractère spécial",
     *     groups="registration"
     * )
     * @Assert\Length(max=8,min=8,exactMessage="la longeur doit être de 8 caractères",
     *     groups="registration")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Email(message="l'email doit être valide")
     */
    private $mail;

    /**
     * @ORM\ManyToOne(targetEntity=Roles::class, inversedBy="users")
     */
    private $id_role;

    /**
     * @Assert\EqualTo(propertyPath="password",
     *     message="les mots de passe ne sont pas identiques",
     *     groups="registration")
     */
    private $confirm_password;

    /**
     * @return mixed
     */
    public function getConfirmPassword()
    {
        return $this->confirm_password;
    }

    /**
     * @param mixed $confirm_password
     */
    public function setConfirmPassword($confirm_password): void
    {
        $this->confirm_password = $confirm_password;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = password_hash($password,PASSWORD_BCRYPT);

        return $this;
    }

    public function getMail(): ?string
    {
        return $this->mail;
    }

    public function setMail(?string $mail): self
    {
        $this->mail = $mail;

        return $this;
    }

    public function getIdRole(): ?Roles
    {
        return $this->id_role;
    }

    public function setIdRole(?Roles $id_role): self
    {
        $this->id_role = $id_role;

        return $this;
    }

    public function getRoles(): ?array
    {
        return array('Role_'.strtoupper($this->id_role()));
    }

    public function getSalt()
    {
        // TODO: Implement getSalt() method.
    }

    public function eraseCredentials()
    {
        // TODO: Implement eraseCredentials() method.
    }

    public function __call(string $name, array $arguments)
    {
        // TODO: Implement @method string getUserIdentifier()
    }
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\Roles;
use App\Entity\Users;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('username',TextType::class)
            ->add('password',PasswordType::class)
            ->add('confirm_password',PasswordType::class)
            ->add('mail',EmailType::class)
            ->add('idRole', EntityType::class,[
                'class'=>Roles::class,
                'choice_label'=> 'label'
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Users::class,
            "Validation_groups"=>["Default","registration"],
        ]);
    }
}

src/Controller/HelloController.php
<?php

namespace App\Controller;

use Psr\Log\LoggerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpKernel\Log\Logger;
use Symfony\Component\Routing\Annotation\Route;

class HelloController extends AbstractController
{
    protected $logger;
    private $title = "Hello ";
//    /**
//     * @Route("/hello", name="app_hello")
//     */
    /**
     * @param LoggerInterface $logger
     */
    public function __construct(LoggerInterface $logger){
        $this->logger = $logger;
    }

    /**
     * @Route("/test/{name?world}",name="test",methods={"GET","POST"},host="localhost",schemes={"http","https"})
     */
    public function test($name){
        $this->title.=$name;
        return $this->render('View/item/hello.html.twig',["title"=>$this->title]);
    }
}

src/Controller/IndexController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Routing\Annotation\Route;

class IndexController extends AbstractController
{
    private $title = "Bienvenue sur la première page du site.";

    /**
     * @Route("/",name="index")
     */
    public function index()
    {
        return $this->render('View/index.html.twig',["title"=>$this->title,"age"=>18]);
    }
}

templates/View/index.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <script src="{{ asset( 'Javascript/Listener.js') }}"></script>
    <link rel="stylesheet" href="{{ asset('CSS/css.css') }}">
    <h1> {{ title }}</h1>
    {% for type,messages in app.flashes %}
        {% for message in messages %}
            <h3>{{ message }}</h3>
            <div class="toast ml-auto" style="position: absolute; top: 5rem; right: 1rem;" role="alert" aria-live="assertive" data-delay="4000" aria-atomic="true">
                <div class="toast-header">
                    <strong class="mr-auto">Error</strong>
                    <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="toast-body">
                    <h2 class="text-danger"> {{ message }}</h2>
                </div>
            </div>
        {% endfor %}
    {% endfor %}
    {% if age is defined %}
        {% if age < 18 %}
            <p>tu es mineur</p>
        {% elseif age >= 18 %}
            <p>tu es majeur</p>
        {% endif %}
    {% endif %}
{% endblock %}

templates/View/item/hello.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <h1>{{ title }}</h1>
{% endblock %}

templates/base.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Welcome!{% endblock %}</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-
        ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://kit.fontawesome.com/ee896b6519.js" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://bootswatch.com/4/flatly/bootstrap.min.css">

    <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
    {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
    {% block stylesheets %}
        {{ encore_entry_link_tags('app') }}
    {% endblock %}

    {% block javascripts %}
        {{ encore_entry_script_tags('app') }}
    {% endblock %}
</head>
<body>
{#    {% set filter = app.session.get('filter') %}#}
{#    {% if filter != null %}#}
{#        {% set idRole = filter['idRole'] %}#}
{#        {% set idUser = filter['idUser'] %}#}
{#        {% set username = filter['username'] %}#}
{#    {% endif %}#}
{% if app.user != null %}
    {% set role = app.user.roles[0] %}
    {% set idUser = app.user.id %}
    {% set username = app.user.username %}
{% endif %}
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container-fluid">
        <a class="navbar-brand" href="/">Ecommerce</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav me-auto">
                <li class="nav-item">
                    <a class="nav-link active" href="/">Home
                        <span class="sr-only">(current)</span>
                    </a>
                </li>
                {# <li class="nav-item">#}
                {# <a class="nav-link" href="{{ path("test",{"name":"xavier"})
}}">Créer un article</a>#}
                {# </li>#}

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-toggle="dropdown"
                       href="#" role="button" aria-haspopup="true" aria-expanded="false">Dropdown</a>
                    <div class="dropdown-menu">
                        {% if role is defined and role =="ROLE_ADMIN" %}
                            <a class="dropdown-item" href="{{ path('account') }}">Créer un utilisateur</a>
                        {% endif %}
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <a class="dropdown-item" href="#">Something else here</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Separated link</a>
                    </div>
                </li>
            </ul>
        </div>
        {% if username is not defined %}
            <ul class="nav navbar-nav flex-row justify-content-between ml-auto">
                <li class="dropdown order-1">
                    <button type="button" id="dropdownMenu1" data-toggle="dropdown" class="btn btn-outline-secondary dropdown-toggle">Login <span class="caret"></span></button>
                    <ul class="dropdown-menu dropdown-menu-right mt-2">
                        <li class="px-3 py-2">
                            <form class="form" role="form"  method='post' action="{{ path('login') }}">
                                <div class="form-group">
                                    <input id="username" name="username" placeholder="Username" class="form-control form-control-sm" type="text" required="">
                                </div>
                                <div class="form-group">
                                    <input id="password" name="password" placeholder="Password" class="form-control form-control-sm" type="password" required="">
                                </div>
                                <div class="form-group">
                                    <button type="submit" class="btn btn-primary btn-block">Login</button>
                                </div>
                                <div class="form-group text-center">
                                    <small><a href="#" data-toggle="modal" data-target="#modalPassword">Forgot password?</a></small>
                                </div>
                                <div class="form-group">
                                    <input name="csrf_token" type="hidden" value="{{ csrf_token('login_form') }}">
                                </div>
                            </form>
                        </li>
                    </ul>
                </li>
            </ul>

        {% else %}
            <ul class="nav navbar-nav flex-row justify-content-between ml-auto">
                <li class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Bienvenue {{ username }}</a>
                    <div class="dropdown-menu">
                        <a href="{{ path('account-edit',{'id':idUser}) }}" class="dropdown-item">Mon Compte</a>
                    </div>
                </li>
                <li class="nav-item nav-link">
                    <i data-toggle="tooltip" data-placement="buttom" title="logout" onclick="location.href='{{ path("logout") }}'" class="fas fa-sign-out-alt"></i>
                </li>
            </ul>

        {% endif %}
    </div>
</nav>
{% block body %}

{% endblock %}
</body>
</html>